### ISSUE TITLE
Issues with argparser on wham dataset

### ISSUE THREAD

**Issue by sunits** [mpariente/AsSteroid#11]
>>  bash run.sh --stage 3 --python_path python
Results from the following experiment will be stored in exp/train_convtasnet_sep_clean_8kmin_009b94e6
Stage 3: Training
usage: train.py [-h] [--use_cuda USE_CUDA] [--model_path MODEL_PATH]
                [--n_filters N_FILTERS] [--kernel_size KERNEL_SIZE]
                [--stride STRIDE] [--n_blocks N_BLOCKS]
                [--n_repeats N_REPEATS] [--mask_act MASK_ACT]
                [--epochs EPOCHS] [--half_lr HALF_LR]
                [--early_stop EARLY_STOP] [--max_norm MAX_NORM]
                [--checkpoint CHECKPOINT] [--continue_from CONTINUE_FROM]
                [--optimizer OPTIMIZER] [--lr LR]
                [--weight_decay WEIGHT_DECAY] [--train_dir TRAIN_DIR]
                [--valid_dir VALID_DIR] [--task TASK]
                [--nondefault_nsrc NONDEFAULT_NSRC]
                [--sample_rate SAMPLE_RATE] [--mode MODE]
                [--batch_size BATCH_SIZE] [--num_workers NUM_WORKERS]
train.py: error: argument --continue_from: invalid NoneType value: ''

**Comment by mpariente** [comment]
Thank for reporting the bug. 
This is because conf.yml returns `None` when the field is empty, so the parser expects a `NoneType` (which is definitely wrong), and bash cannot pass `None` to python. 
I'll commit a quick fix now and write proper checks on the parser tomorow.

**Comment by mpariente** [comment]
[This commit](https://github.com/mpariente/AsSteroid/commit/1f10922b72f983f2969e3c5ed9027f4912585fc2) should temporarly fix it.
