### ISSUE TITLE
Call to Filterbanks fail

### ISSUE THREAD

**Issue by sunits** [mpariente/AsSteroid#12]
Running  this [code](https://github.com/mpariente/AsSteroid/files/3855451/testSTFT.txt)  gives the following error:
> Illegal instruction

The error happens for both enc and fenc. I am running pytorch version 1.1.0. 
Similar issues while running the wham baseline.

**Comment by mpariente** [comment]
I tried with pytorch 1.1.0, 1.3.0 and 1.3.1 and the code compiles in the three cases..
Can you be sure that the problem is with the filterbank call? [This issue could be related](https://github.com/pytorch/pytorch/issues/2714), what's the output of  `cat /proc/cpuinfo`?

**Comment by mpariente** [comment]
Any update on this? Did you try re-install?

**Comment by sunits** [comment]
I created a new conda environment using the requirements file. Worked fine in that environment.
