### ISSUE TITLE
Container issues

### ISSUE THREAD

**Issue by sunits** [mpariente/AsSteroid#16]
1. How to handle multi output coming from masker? Example, clustering output and mask in case of Deep clustering. Right now the masker expects only a single output
2. Applying the mask: I need to apply the mask on the masker input (magnitude spectra and not the real and imaginary part). Will have to rethink the design

**Comment by mpariente** [comment]
- The `Container` is quite limited for now and I'm not sure it makes sense to try and fit all `forward` into one class. Probably the solution will be to subclass it (but I'll try to find something clever to keep the saving and loading practical as it is now).
- For the masking, a `'mag'` mask is a magnitude mask which is applied to the complex representation. It's strictly equivalent to a magnitude mask, but the phase is kept so the resynthesis can be done.

**Comment by mpariente** [comment]
Solved by #19
