### ISSUE TITLE
Post processing encoder/decoder

### ISSUE THREAD

**Issue by sunits** [mpariente/AsSteroid#17]
I want to take the log of mag spec before passing it to the masker but the current post_process_inputs calls inp_func() with predefined set of options. Perhaps it makes sense to keep this flexible, with a callback function?

**Comment by mpariente** [comment]
As in #16, it doesn't make sense to try to cover all the usecases under one class, it'll just be growing as new architectures come in. Let's try to find something else.

**Comment by mpariente** [comment]
Solved by #19
