### ISSUE TITLE
FurcaNeXt

### ISSUE THREAD

**Issue by ujscjj** [mpariente/AsSteroid#20]
Hello, thank you for your work. When will you upload the codes about 'FurcaNeXt'?

**Comment by mpariente** [comment]
Hi, thanks for your interest in asteroid !
I didn't code the architecture yet, sorry.
The priority is to get the `ConvTasNet` recipe working from beginning to end (including computing the evaluation metrics which I'm working on right now). This will make FurcaNeXt recipe very easy to write, as soon as the architectures are in the `asteroid`. Coding the architecture is not a high priority for us so if you want to integrate it faster, please feel free to make a pull request.
